### ISSUE TITLE
Change canonical_with_ranks to canonical_complete

### ISSUE THREAD

**Issue by dimus** [GlobalNamesArchitecture/gnparser#123]
Paddy suggested to have 2 version of canonical -- one which is identical to canonical we have, and another one that contains everything from 'normalized' version except authors. Canonical_complete practically speaking is the same as canonical_with ranks plus showing subgenus.

**Comment by alexander-myltsev** [comment]
We would have 3 forms of canonical then so far. I suggest to put all 3 forms inside `canonical` node in the output json. WDYT?

**Comment by dimus** [comment]
Lets leave it as if for now, according to discussion we had with Rich.
