### ISSUE TITLE
id calculation problem due to default encoding

### ISSUE THREAD

**Issue by alexander-myltsev** [GlobalNamesArchitecture/gnparser#14]
GNParser uses `org.apache.commons.id.uuid.UUID.nameUUIDFromString` from [littleshoot-commons-id](https://github.com/adamfisk/littleshoot-commons-id) library. And it has a bug: it uses default encoding [when gets bytes](https://github.com/adamfisk/littleshoot-commons-id/blob/master/src/main/java/org/apache/commons/id/uuid/UUID.java#L430). If default encoding is UTF8 (that is on *nix) then all is fine. On Win it might be Cp1251 that breaks everything.

Workaround is to launch sbt with opts: `JAVA_OPTS="-Dfile.encoding=UTF8" sbt`

**Comment by dimus** [comment]
Good to know. We need to add it to README
