### ISSUE TITLE
Create automated markdown doc generation for  JSon fields

### ISSUE THREAD

**Issue by alexander-myltsev** [GlobalNamesArchitecture/gnparser#157]
Now we have `JSON_FIELDS.md` that informally describes fields. For example, we can neither verify the document nor verify some JSon with it. 

What we need is: 
* JSon schema v4 description ([example](http://json-schema.org/example2.html)) 
* markdown generation template similar to [this one](https://github.com/interagent/prmd/blob/master/lib/prmd/templates/schemata.md.erb)
* and, finally, complete workflow (sbt task?) to generate MD description with https://github.com/interagent/prmd

**Comment by alexander-myltsev** [comment]
Additionally we could apply JSon schema validation to tests.

**Comment by dimus** [comment]
schema validation for tests would make a lot of sense, should be a separate ticket though

**Comment by dimus** [comment]
*  http://orderly-json.org/ to describe fields
*  json-schema generated from orderly
*  https://github.com/interagent/prmd template for converting  json-schema  to markdown: https://github.com/interagent/prmd/blob/master/lib/prmd/templates/schemata.md.erb
* Use template with https://github.com/interagent/prmd to make  markdown
* creaate sbt subtask with all this `sbt doc`

alexander_myltsev [5:25 AM]
https://github.com/lloyd/orderly is dead

https://github.com/interagent/prmd is alive

**Comment by alexander-myltsev** [comment]
Seems like we can't use custom erb templates in https://github.com/interagent/prmd. We need to discuss.
