### ISSUE TITLE
Parse names with authors like Jack.-Drake.

### ISSUE THREAD

**Issue by dimus** [GlobalNamesArchitecture/gnparser#218]

**Comment by alexander-myltsev** [comment]
Add `Pseudocercospora Speg., Jack.-Drake.` to `# Uninomial with an author<` section.

**Comment by alexander-myltsev** [comment]
@dimus , can author be like `Firstname Jack.-Drake.`?

**Comment by alexander-myltsev** [comment]
Forget my last question. It was easier to implement it in that way.
