### ISSUE TITLE
Replace docker dedicated project with gnparser docker stage/publish sbt-task

### ISSUE THREAD

**Issue by alexander-myltsev** [GlobalNamesArchitecture/gnparser#250]

**Comment by alexander-myltsev** [comment]
@dimus , currently https://github.com/gn-docker/gnparser puts both `runner` and `web` into a docker whereas those two projects are mutually independent. I suggest to put those to different dockers. WDYT?

**Comment by dimus** [comment]
С точки зрения пользователя на мой взгляд неудобно -- я считаю лучше в один проект совместить. В смысле  SBT так не выходит?

**Comment by alexander-myltsev** [comment]
I see no big problems to launch docker via two separate commands as followsЙ

```
docker run -d -p 80:9000 --name gnparser gnames/gnparser-web
docker run -d -p 4334:4334 --name gnparser gnames/gnparser-runner
```

On the other hand we had to compose dedicated project in SBT that would refer `web` and `runner` to produce a docker. And also a user would has to download both `web` and `runner` content in a docker even if he is only interested in a single one. What are your objections to host two separate dockers? 

P.S.: You wrote in Russian :)

**Comment by dimus** [comment]
I suspect two containers doing 2 similar things will bring confusion kind of like if using nginx for tcp/ip and http would require to download two separate packages
