### ISSUE TITLE
Authors might have apostrophe

### ISSUE THREAD

**Issue by dimus** [GlobalNamesArchitecture/gnparser#251]
`Betula ferganensis Vasil'ev`
`Nereidavus kulkovi Kul'kov in Kul'kov & Obut, 1973`

**Comment by alexander-myltsev** [comment]
Space in `Vasil 'ev`?

**Comment by dimus** [comment]
No, no space

**Comment by alexander-myltsev** [comment]
OK. Fixed your first comment then.
