### ISSUE TITLE
Introduce approximate year

### ISSUE THREAD

**Issue by dimus** [GlobalNamesArchitecture/gnparser#27]

**Comment by dimus** [comment]
Currently when we normalize year we mix two different categories. When year is just like `1789`, `1789a` there is no indication that the person who entered name is in doubt about its accuracy. In situations like `1789?`, `178?`, `1789-82`, `(1789)`, `[1789]` it is stated that the year is not defined for sure. We need a new qualifier `approximate_year` and in normalized version the year should be in parentheses -- `1789`

**Comment by alexander-myltsev** [comment]
Should `"year"` node in `details` json have `approximate` field?

**Comment by alexander-myltsev** [comment]
In `details` year's `"str"` field should be without parentheses, right?
