### ISSUE TITLE
use parsing quality result as a component to calculate a matching score

### ISSUE THREAD

**Issue by dimus** [GlobalNamesArchitecture/gnparser#291]
For example if canonical form had been generated from a name string with parsing problems -- penalize resulting score for matches with such canonical form. For example see comment from 

https://github.com/GlobalNamesArchitecture/gni/issues/48#issuecomment-218235801

**Comment by alexander-myltsev** [comment]
Issue moved to [GlobalNamesArchitecture/gnresolver #36](https://github.com/GlobalNamesArchitecture/gnresolver/issues/36) via [**ZenHub.io**](https://www.zenhub.io/)
