### ISSUE TITLE
hyphenated genus name with capitalized part e.g. Saxo-Fridericia

### ISSUE THREAD

**Issue by jar398** [GlobalNamesArchitecture/gnparser#320]
The following scientificName is from GBIF record 7641405:

`Saxo-Fridericia R. H. Schomb.`

The parser does not parse it. Other examples include Cyrto-Hypnum and its species.

Not sure whether you _want_ it to parse, as you might consider this an error. I've found these in the wild, and not just in GBIF. Thought you should know. The fix would be to recognize it and lowercase the letter after the hyphen.

**Comment by dimus** [comment]
yes, these are historically used spellings, so we need to cover them

**Comment by alexander-myltsev** [comment]
merged in 4fc8b67b163cf1efc532f0a8b443a007a0d258c9

**Comment by jar398** [comment]
According to Rick Ree, all of these should canonicalize to lower case for the letter after the hyphen. That is, he has told me to make e.g. Complanato-Hypnum a synonym (spelling variant) for Complanato-hypnum, not the other way around. The Plant List concurs, e.g. http://www.theplantlist.org/tpl1.1/record/tro-35157955 . Wikipedia also concurs, see https://en.wikipedia.org/wiki/Saxo-fridericia. I would be surprised if the code dictates lower case, but I haven't checked.

**Comment by dimus** [comment]
I do not see anything in the ICN about decapitalization, but there are no examples with capitalized letter after the dash.

20.3. The name of a genus may not consist of two words, unless these words are joined by a hyphen.
Ex.7. “Uva ursi”, as originally published by Miller (1754), consisted of two separate words unconnected by a hyphen, and is not therefore validly published (Art. 32.1(c)); the name is correctly attributed to Duhamel (1755) as Uva-ursi (hyphenated when published).
Ex.8. Names such as Quisqualis L. (formed by combining two words into one when originally published), Neves-armondia K. Schum., Sebastiano-schaueria Nees, and Solms-laubachia Muschl. ex Diels (all hyphenated when originally published) are validly published.

According to @proceps dashes in genera are not legal in ICZN
