### ISSUE TITLE
README.md - 'description of json fields' link broken

### ISSUE THREAD

**Issue by mjy** [GlobalNamesArchitecture/gnparser#324]

**Comment by alexander-myltsev** [comment]
Oops. It was deleted at https://github.com/GlobalNamesArchitecture/gnparser/commit/1d6ded7d2a5511544f7b06545c4572b4c1735aed 

@dimus , do you remember the exact reason we decide to do it? There was some story with JSON schema, then we observed JSON schema doesn't work properly.

**Comment by dimus** [comment]
I changed link to JSON schema
