### ISSUE TITLE
Unable to run R example

### ISSUE THREAD

**Issue by kds15e** [GlobalNamesArchitecture/gnparser#325]
When I try to run the following line in the R example of gnparser:
snp=J('org.globalnames.parser.ScientificNameParser','instance')

I get the following error:
Error in .jfindClass(o) : class not found

**Comment by alexander-myltsev** [comment]
Double check `pathToGnParserAssembly`. Note that `GnParser_PATH` in
`pathToGnParserAssembly='${GnParser_PATH}/gnparser/parser/target/scala-2.11/global-names-parser-assembly-0.1.0-SNAPSHOT.jar'
.jinit(classpath=pathToGnParserAssembly)` should be substituted, so that `pathToGnParserAssembly` points to correct `jar` (that is currently of [version 0.3.3](https://github.com/GlobalNamesArchitecture/gnparser/releases/tag/release-0.3.3))

**Comment by dimus** [comment]
Closing this one, @kds15e if you will still have a problem after making sure your path is set correctly, please reopen and continue with this ticket

**Comment by alexander-myltsev** [comment]
@kds15e , I suggest you to check https://github.com/GlobalNamesArchitecture/gnparser/pull/345/commits/e30fa5b20d3f7b39786d6f6ddd0cc515a82c36d7 . `R` example is testable at circleci now.

**Comment by kds15e** [comment]
Thanks for the useful code! Unfortunately, I'm coming up with the following error:

> snp=J('org.globalnames.parser.ScientificNameParser','instance')
> Error in .jfindClass(o) : class not found

Am I missing a package? I loaded rJava and jsonlite and have run all the preceding code for the Test R example.

**Comment by alexander-myltsev** [comment]
Did you make an assembly with `sbt parser/assembly`? If not (or you wouldn't like to), please download gnparser-assembly-0.3.3.jar from [releases](https://github.com/GlobalNamesArchitecture/gnparser/releases/tag/release-0.3.3).

**Comment by kds15e** [comment]
Awesome, done! Now how do I get it to actually parse? jsonResult$parsed remains false when I input my own string. Am I missing the point of this code?
Sorry for my ignorance; I'm new at this :)

**Comment by alexander-myltsev** [comment]
`jsonResult` stores `JSON`. Try to parse [`Homo sapiens`](http://parser.globalnames.org/?q=Homo+sapiens+Linnaeus+1758) and check the result JSON.

`parsed == false` means that name is not parsed. That in turn means that your name is either wrong, or in that rare .01% that can't be currently parsed. What's the name?

**Comment by kds15e** [comment]
Will it only parse a string that consists solely of a taxonomic name, rather than extracting taxonomic names from within a string? For example, I want to parse the scientific name (e.g., Cyperus croceus) out of a string like this "On moist clayey soil with Cyperus croceus and other sedges."

**Comment by dimus** [comment]
It is not for finding names in strings. There is another [tool](http://gnrd.globalnames.org) for that. You can try gnparser [online](http://parser.globalnames.org), it will show you what it can do.

**Comment by kds15e** [comment]
Hi dimus,
That's what I was afraid of...
Yes, I am aware of (and greatly appreciate!) the online gnparser tool. What I've been trying to do is parse and retrieve data from many strings in succession. I developed an R code that does this, but I have been unsuccessful at putting the code in a functional loop (https://github.com/jeroenooms/curl/issues/92).

**Comment by dimus** [comment]
To make GNRD API work for your loop you need to add internal loop that would continue to check if there the results are ready at the token url. If they are not ready yet, wait a bit, and then try again. When you see that results are prepared you can proceed with downloading them. You will know that results are ready if JSON has ``names`` field, which can be either empty or have some names in it.
