### ISSUE TITLE
Arctostaphylos preglauca cf. should work similar to Arctostaphylos preglauca sp.

### ISSUE THREAD

**Issue by dimus** [GlobalNamesArchitecture/gnparser#327]
Right now `Arctostaphylos preglauca cf.` is parsed to a canonical like `Arctostaphylos preglauca cf`
i.e. `cf` is parsed like infraspecific epiethet.

Behavior should be similar to names where `ssp.` happens after species and is the last word:

`Alyxia reinwardti ssp.
{"name_string_id":"72b5072a-d952-54f8-aea1-5b5bd3c65c45","parsed":true,"quality":2,"quality_warnings":[[2,"Name had to be changed by preprocessing"]],"parser_version":"test_version","verbatim":"Alyxia reinwardti ssp.","normalized":"Alyxia reinwardti","canonical_name":{"value":"Alyxia reinwardti"},"hybrid":false,"surrogate":false,"virus":false,"details":[{"genus":{"value":"Alyxia"},"specific_epithet":{"value":"reinwardti"}}],"positions":[["genus",0,6],["specific_epithet",7,17]]}
72b5072a-d952-54f8-aea1-5b5bd3c65c45|Alyxia reinwardti ssp.|Alyxia reinwardti|Alyxia reinwardti|||2
`

**Comment by alexander-myltsev** [comment]
`cf.` should be of same behaviour as `spp.` etc.

Also take close attention to changed tests.

**Comment by dimus** [comment]
We talked again with Yury, and came to a conclusion that the way we are dealing with sp. cf. and aff. does make sense actually. So lets leave existing tests as they are

**Comment by alexander-myltsev** [comment]
Consider `Formicidae cf.`. It should stay `surrogate: true` and warning level 3 of `"Name comparison"`.
