### ISSUE TITLE
Acanthoderes (acanthoderes) satanas Aurivillius, 1923 --- superspecies

### ISSUE THREAD

**Issue by dimus** [GlobalNamesArchitecture/gnparser#328]
`Acanthoderes (acanthoderes) satanas Aurivillius, 1923` righ now stop parsing after genus with resulting canonical name `Acanthoderes`. It seems that we have cases where `(acanthoderes)` part would be either misspelled subgenus or legitimate superspecies. Looks like quite often it is just a misspelling, so I propose to ignore `(acanthoderes)` part completely. in normalized version and in details.

**Comment by alexander-myltsev** [comment]
Drop off that ambiguity of `subgenus` or `superspecies`. Give `warning 2`.
