### ISSUE TITLE
"v." in "Orthosia kindermannii Fischer v. Roslerstamm, 1837" is the same as "von"

### ISSUE THREAD

**Issue by dimus** [GlobalNamesArchitecture/gnparser#329]
Authors prefix "v." should be taken into account and normalized to `von` in names like 

`Orthosia kindermannii Fischer v. Roslerstamm, 1837` which is the same as 
Orthosia kindermannii Fischer von Roslerstamm, 1837

**Comment by alexander-myltsev** [comment]
`v.` should be in canonical name as is.
