### ISSUE TITLE
"Papyrus tubiferus Schrad. ex. Steud." parses "ex" as infraspecific epithet

### ISSUE THREAD

**Issue by dimus** [GlobalNamesArchitecture/gnparser#330]
`Papyrus tubiferus Schrad. ex. Steud.` parses "ex" as infraspecific epithet:

canonical --- `Papyrus tubiferus ex` and authorship is `Nothing`.  

so it considers that name ends with a `period` but in reality it is a mistake in the way people wrote `ex` -- it supposed to be without a dot. I guess it wont hurt to add `ex.` to the rule with `ex and in`  but give a warning that the name is not correctly spelled.

**Comment by alexander-myltsev** [comment]
Should `ex.` be with dot in canonical name or not?
