### ISSUE TITLE
Figure out what to do with "le"

### ISSUE THREAD

**Issue by dimus** [GlobalNamesArchitecture/gnparser#331]
Looks like "le" is used as part of an author and as part of a specific epithet. I also have a suspision that names with "le" as specific epithet are really have epithet separated by a space!

http://gni.globalnames.org/name_strings?commit=Search&page=2&search_term=sp%3Ale

We probably should make a dictionary where it is an author and where it is a name, and normalize them accordingly... Big job.

**Comment by alexander-myltsev** [comment]
Can `le` be a species name on its own? Consider `Neoleptura le subsp. contei Thomson, 1860`.

**Comment by dimus** [comment]
https://gitlab.com/gogna/gnparser/issues/53

Closing here
