### ISSUE TITLE
Support STDIN for runner

### ISSUE THREAD

**Issue by alexander-myltsev** [GlobalNamesArchitecture/gnparser#346]

**Comment by alexander-myltsev** [comment]
@dimus , how should it be in the end? `gnparser --input - --output -`?

**Comment by dimus** [comment]
The best way would be to have STDIN and STDOUT a default, and --input --output an option, like for example 
```bash
cat file | gnparser > res
```

**Comment by alexander-myltsev** [comment]
@dimus  Looking and your command name, I suppose it is more natural to call command `gnparser` instead of `gnparse`. What do you think?

**Comment by dimus** [comment]
+1 for gnparser instead of gnparse
