### ISSUE TITLE
How can I access the rest service hosted in Docker

### ISSUE THREAD

**Issue by yukund** [GlobalNamesArchitecture/gnparser#349]
Hi Gnparser team 

I would like to know how to access the rest service.

I have started the docker container with 
~$ docker run -p 80:9000 --name gnparser gnames/gnparser web
Server online at http://0.0.0.0:4334/

In order to access the rest service, should I use port 4334 or 9000 ie. http://localhost:9000/api?q="..." ? 

Thank you 
Yanbo

**Comment by yukund** [comment]
I mapped port 4334 to 80, it is working now. Please close the ticket.
~$ docker run -p 80:4334 --name gnparser gnames/gnparser web

**Comment by alexander-myltsev** [comment]
👍
