### ISSUE TITLE
dash in specific epithet

### ISSUE THREAD

**Issue by diatomsRcool** [GlobalNamesArchitecture/gnparser#361]
gnparser cannot parse the following
Sanogasta x-signata (Keyserling,1891)
Zygiella x-notata (Clerck, 1757)
I think it is because of the "-"

**Comment by alexander-myltsev** [comment]
Is it required to have some additional indication that `x-name` was parsed? Like boolean property or warning?

**Comment by diatomsRcool** [comment]
No special warning needed. Right now I give it Sanogasta x-signata (Keyserling,1891) and I get back Sanogasta x-signata (Keyserling,1891). It doesn't seem to know what to do with it. I just need it to recognize x-signata as a specific epithet so I can get back the canonical name without the authority. Does that make sense?

**Comment by alexander-myltsev** [comment]
It does. Can `x-` prefix be for genus? Like `X-Sanogasta x-signata`?

**Comment by diatomsRcool** [comment]
I have never, ever, seen x- in a genus, but that doesn't mean that somewhere some taxonomist didn't decide to do it. A quick search of EOL returned nothing. I wouldn't allow for it at this point.

**Comment by dimus** [comment]
Our zoological commissioner says  no dashes allowed in genera

**Comment by dimus** [comment]
Looking into gni db and I am finding a lot of variety
```
Ctenoplon x-littera (Thomson, 1865)
Cteniscus t-nigrum Thomson 1883
Deporaus (Pseudodeporaus) v-rubra Voss , 1942
Dafa m-clementinella Costa 1836
Dasypogon g-fasciatus
Cynortopyga h-album Roewer 1947
Cyaniris c-nigrum Tutt 1909
etc...
```
So i guess we have to bite the bullet and ad all [a-z] as a possiblility. However it does break a few tests too :-/

**Comment by dimus** [comment]
Altogether we have 4k namestrings of this sort, but if to take out viruses, lexical variants -- I think it comes to ~800 names

**Comment by dimus** [comment]
We found 3 algae with dashes :-/ (they are in algaebase, but apparently dashes in genera are not legal)

Pseudo-eunotia Pseudo-nitzschia Pseudo-pleurosigma
