### ISSUE TITLE
dela as specific epithet

### ISSUE THREAD

**Issue by diatomsRcool** [GlobalNamesArchitecture/gnparser#363]
gnparser strips the "dela" specific epithet off of Tortolena dela. I assume becase "de la" is a common part of an authority as well.

**Comment by diatomsRcool** [comment]
Same with "van" in Zodarion van

**Comment by diatomsRcool** [comment]
And Selenops ab

**Comment by dimus** [comment]
hm, sounds like a battle between precision and recall, so I wonder what is better to do in cases like this

**Comment by dimus** [comment]
I wonder if the best scenario here is to keep a white list of known cases :-/

**Comment by diatomsRcool** [comment]
Well, I'm running a lot through gnparser (worms and gbif) and these are the only ones I've found. So, that might be best.

**Comment by diatomsRcool** [comment]
More for the "white list"
Boreophilia nomensis
Ruteloryctes bis
phelodon nomene
Paralvinella dela
Gnathopleustes den

**Comment by diatomsRcool** [comment]
And still more
Agathidium nudum
Trachyphloeosoma nudum
Aphaniosoma nudum
Africanthion nudum
Bottaria nudum

**Comment by dimus** [comment]
`Agathidium nudum`? Oh my

**Comment by alexander-myltsev** [comment]
Related to https://github.com/GlobalNamesArchitecture/gnparser/issues/331

**Comment by dimus** [comment]
Closing here opening https://gitlab.com/gogna/gnparser/issues/53
