### ISSUE TITLE
Figure out what to do with showing help 

### ISSUE THREAD

**Issue by alexander-myltsev** [GlobalNamesArchitecture/gnparser#375]
> We figured out what’s wrong with `gnparser` launch script. `sbt-native-packager` team just changed the environment, so our bash template stopped working. I would add tests to CircleCI to prevent it in future.

> The reason we established custom `gnparser` template is custom help messages. Java launcher script uses `-h | -help` to show bash-specific help. scopt/twitter finagle uses `--help`. Consider https://github.com/sbt/sbt-native-packager/issues/831. We need to discuss the way to combine them to drop that bash template.

> A way we can solve it is to show help when no args are given. currently we launch web-server by default. but since native-packager generates web-serverscript for Play servers, I think we could give it a try.

We need to figure out how to merge those two helps.

**Comment by dimus** [comment]
Solved in https://gitlab.com/gogna/gnparser
