### ISSUE TITLE
authorities confused as subgenera

### ISSUE THREAD

**Issue by diatomsRcool** [GlobalNamesArchitecture/gnparser#376]
Having issues with genera like Cheilolejeunea (Spruce) Steph. The "Spruce" is being interpreted as a subgenus, when it is an authority. In the botanical code the original authority is often retained and placed in parentheses after someone else (in this case "Steph.") has revised the genus. I think the Genus (Subgenus) pattern is common in the zoological code. We need to be able to tell the difference and get it right.

**Comment by diatomsRcool** [comment]
This is a big problem and we would like to have it prioritized, if possible.

**Comment by dimus** [comment]
It is a known problem, and very hard to solve. Probably we need a list of known generic authors for plants and if 'subgenus' matches that list -- declare it an author. Moving it to Go gnparser.

https://gitlab.com/gogna/gnparser/issues/51
