### ISSUE TITLE
numbers in specific epithet

### ISSUE THREAD

**Issue by diatomsRcool** [GlobalNamesArchitecture/gnparser#377]
I have been made aware of some insect names that have numbers in the specific epithet. Apparently, this was common in the "old days". These are names in gbif.
Curculio 2tuberculatus Fabricius, 1781
Coccinella 9maculata Fabricius, 1781
Reduvius 2pustulatus
Camponotus 4maculatus
Coccinella 6maculata Fabricius, 1781
Copris 4dentatus Fabricius, 1798
Coccinella 8maculata Fabricius, 1781

**Comment by diatomsRcool** [comment]
After speaking with Katja, we think these might be fishy names, but parser needs to be able to cope. We are going to throw these away, so fixing this is not a priority for us.

**Comment by dimus** [comment]
Closing. Covered in [Go gnparser](http://parser.globalnames.org/?q=Curculio+2tuberculatus+Fabricius%2C+1781%0D%0ACoccinella+9maculata+Fabricius%2C+1781%0D%0AReduvius+2pustulatus%0D%0ACamponotus+4maculatus%0D%0ACoccinella+6maculata+Fabricius%2C+1781%0D%0ACopris+4dentatus+Fabricius%2C+1798%0D%0ACoccinella+8maculata+Fabricius%2C+1781)
