### ISSUE TITLE
capitalized epithets

### ISSUE THREAD

**Issue by diatomsRcool** [GlobalNamesArchitecture/gnparser#378]
I have been made aware of the following taxa that are not parsed properly, likely because they have capitalized epithets.
Tanais Grimaldii Dollfus, 1897
Microstomum Jenseni Riedel, 1932
Tvaerminnea Karlingi Luther, 1943
Tanais Gayi Nicolet, 1849 
Denticulella Benthica Dashchenko, 2002
Denticulella Boreala Dashchenko, 2002
They may not be allowed now, but at one time they were. I know I've seen them in botanical names.

**Comment by dimus** [comment]
I've seen this kind a lot in old literature, not sure what to do with them. They are historical and 'real', but they bring a little gain in recall with huge loss in precision :-/

**Comment by diatomsRcool** [comment]
another white list issue?

**Comment by dimus** [comment]
I think this is 'no fix' case. I see such names a lot in horticultural literature, and there is no way to predict such what names will be capitalized. Similar issue would be low cap  genus. I tried to cope with it during name-finding and it generates way to many false positives.
