### ISSUE TITLE
As a User I want parser to work with 'ex', 'ab.', 'ab. n.', 'cv', 'st'

### ISSUE THREAD

**Issue by dimus** [GlobalNamesArchitecture/gnparser#401]
Looks like we have quite a few names with `ex` and `ab`, but I do not know how to handle them correctly. We need to ask around
```
Acidalia remutaria ab. n. undularia
Acmaeops (Pseudodinoptera) bivittata ab. fusciceps Aurivillius, 1912
Acanthochiton ex quisitus
Acastella ex gr. rouaulti
Androlepis skinneri Brongniart ex houllet
Phyllostachys vivax cv aureocaulis
Rhododendron cv Cilpinense
Ligusticum sinense cv 'chuanxiong' S.H. Qiu & et al.
Crematogaster impressa st. brazzai Santschi 1937
Cibotium st.-johnii Krajina
Camponotus conspicuus st. zonatus
```

**Comment by mdoering** [comment]
`ab.` is a legacy rank in zoology, "[Abberation](https://github.com/gbif/gbif-api/blob/master/src/main/java/org/gbif/api/vocabulary/Rank.java#L207)"

`cv`, cultivar is for a cultivated plant name.  [The code](https://en.wikipedia.org/wiki/International_Code_of_Nomenclature_for_Cultivated_Plants) recommends to use single quotes around the cultivar name, normally capitalized

`gr.` looks like a grex name, again from cultivated plants.

`Acanthochiton ex quisitus` looks suspicously like `exquisitus`

`Androlepis skinneri Brongniart ex houllet` is for the ex author Houllet: https://de.wikipedia.org/wiki/Androlepis_skinneri

**Comment by dimus** [comment]
Thanks @mdoering very helpful
