### ISSUE TITLE
Names like "Arv1virus" are broken into "Arv" and "1virus"

### ISSUE THREAD

**Issue by dimus** [GlobalNamesArchitecture/gnparser#408]
number serves as a border for breaking into words, as a result we have genera like 

Arv from Arv1virus

Kpp from Kpp25virus

Cjw from Cjw1virus

Also, we should not see such names parsed because they are viruses.

**Comment by alexander-myltsev** [comment]
Should be working after https://github.com/GlobalNamesArchitecture/gnparser/issues/399

But `virus` field should be also `true`.
