### ISSUE TITLE
Sanctioning authors not parsed

### ISSUE THREAD

**Issue by mdoering** [GlobalNamesArchitecture/gnparser#409]
Fungal names often have a sanctioning author (Fr. or Pers.) following a colon after the basionym or combination authorship. This is currently unparsed.

Example: Boletus versicolor L. : Fr.
ICNfap Article 50: http://www.iapt-taxon.org/nomen/main.php?page=r50E&emph=sanctioned
https://en.wikipedia.org/wiki/Sanctioned_name

**Comment by dimus** [comment]
Closing here -- moved to https://gitlab.com/gogna/gnparser/issues/47
