### ISSUE TITLE
Named hybrid wrongly parsed

### ISSUE THREAD

**Issue by mdoering** [GlobalNamesArchitecture/gnparser#411]
[Named hybrids](https://en.wikipedia.org/wiki/Hybrid_name), i.e. nothotaxa that were given a new latin name with a single hybrid marker indicating the rank of the hybridization are not parsed correctly.

Named hybrids are apparently treated as hybrid formulas and the parser returns even for a well formed name like `Magnolia × soulangeana` a warning [Incomplete hybrid formula](http://parser.globalnames.org/?q=Magnolia+%C3%97+soulangeana)

**Comment by dimus** [comment]
Yes, wrong warning, need to fix that

**Comment by dimus** [comment]
Fixed in https://gitlab.com/gogna/gnparser
