### ISSUE TITLE
"Pelargonium cucullatum ssp. cucullatum (L.) L'Her. ex [Soland.]" should not parse 'ex' as infraspecies

### ISSUE THREAD

**Issue by dimus** [GlobalNamesArchitecture/gnparser#429]
"canonical_name": {
    "value": "Pelargonium cucullatum cucullatum ex",
    "value_ranked": "Pelargonium cucullatum ssp. cucullatum ex"
  },

**Comment by alexander-myltsev** [comment]
What `ex` should be in that case? Author word?

**Comment by alexander-myltsev** [comment]
Don't parse `ex` as species/infraspecies
