### ISSUE TITLE
Parse "nvar." rank

### ISSUE THREAD

**Issue by dimus** [GlobalNamesArchitecture/gnparser#430]
Crataegus curvisepala nvar. naviculiformis T. Petauer

**Comment by alexander-myltsev** [comment]
`var` is also used in https://github.com/GlobalNamesArchitecture/gnparser/blob/17109ca893fcfea15970211a9e2c260b4f664b12/parser/src/main/scala/org/globalnames/parser/Preprocessor.scala#L31-L34 

Should it be extended here too?

**Comment by alexander-myltsev** [comment]
It should be added since `nvar` is very rare.
