### ISSUE TITLE
"Astatotilapia cf. bloyeti OS-2017" parses OS- as author and 2017 as a year incorrectly

### ISSUE THREAD

**Issue by dimus** [GlobalNamesArchitecture/gnparser#432]
Astatotilapia cf. bloyeti OS-2017

**Comment by alexander-myltsev** [comment]
We should determine the properties why `OS-2017` should not be an author. Currently, it does because of the rule

https://github.com/GlobalNamesArchitecture/gnparser/blob/4dc7388c56c808488003ee8712ac4bf640e95198/parser/src/main/scala/org/globalnames/parser/Parser.scala#L576-L580
