### ISSUE TITLE
Header on "file" output

### ISSUE THREAD

**Issue by Mesibov** [GlobalNamesArchitecture/gnparser#438]
When running gnparser with the file command in a BASH shell, stdout has one or more non-JSON header lines (e.g. "Running with parallelism: 4"). These header lines throw up errors in JSON-interpreting programs that use the JSON output from gnparser as stdin. I can remove these header lines if I know how many there are (with tail), but I don't always know that.

**Comment by alexander-myltsev** [comment]
@Mesibov , please, check the 3854e41773b5725ad1c0b31c5c33fb6914e22c1a . Now `gnparser` writes its service information to STDERR. You can redirect the STDOUT right to your formatting util:

```
bash gnparser-0.4.5-SNAPSHOT/bin/gnparser file -i test.txt | python -m json.tool
```

Also, keep track on the https://github.com/GlobalNamesArchitecture/gnparser/issues/465

All the code would be shipped upon the next release.

**Comment by Mesibov** [comment]
@alexander-myltsev 
Many thanks, > stderr is a good solution. Looking forward to the next release.
