### ISSUE TITLE
Several names that are not parsed correctly

### ISSUE THREAD

**Issue by dimus** [GlobalNamesArchitecture/gnparser#452]
``Velutina haliotoides (Linnaeus, 1758), <i>sensu</i> Fabricius, 1780``

gives canonical `Velutina` instead of `Velutina haliotides`

`Architectonica offlexa Iredale, 1931`

gives canonical 'Architectonica` instead of `Architectonica offlexa`

Notopholia corrusca (Nordmann, 1835)

not parsed
instead of giving `Notopholia corrusca` as canonicalNotopholia corrusca (Nordmann, 1835)

`Fusinus eucos�nius`

gets canonical Fusinus should give `Fusinus eucos�nius` with quality score 3 (illegal characters)

`Fusinus clavilithoides Landau, Harzhauser, Büyükmeriç & Breitenberger, 20`

should have canonical `Fusinus clavilithoides`, but gives `Fusinus`

**Comment by alexander-myltsev** [comment]
closed by derived issues
