### ISSUE TITLE
Parser breaks on "</i>Hipponicidae<i>_incertae_sedis</i>"

### ISSUE THREAD

**Issue by dimus** [GlobalNamesArchitecture/gnparser#468]

**Comment by alexander-myltsev** [comment]
Fixed by https://github.com/GlobalNamesArchitecture/gnparser/commit/a8ba09c016ea1c9eb69d8a5a04631cba4897e0ab

**Comment by dimus** [comment]
There is incertae sedis (of uncertain placement in latin) in the name, so it should return similar results to other incerta cedis cases in the test fille. There is a section about such names.
