### ISSUE TITLE
how do you differentiate author strings?

### ISSUE THREAD

**Issue by sckott** [GlobalNamesArchitecture/gnparser#479]
hi @dimus - hope you don't mind a question about how you made this so I can help my R port of this?

Curious how you differentiate author strings from other parts of the name? I can see how it's easier when there's a year given, but how is it done when there's no year present?

**Comment by dimus** [comment]
@skott, probably easier to make a google hangout or skype call about it?

**Comment by dimus** [comment]
I am also wondering if we can do something with my new project: https://gitlab.com/gogna/gnparser

**Comment by sckott** [comment]
a call would be good. Either of those is good for me. What day and time? What time zone are you in?

**Comment by sckott** [comment]
Possibly with the go version. though I think we still don't have a nice Go/R integration that works across platforms, etc. R has great integrations for C and C++, and Rust actually works very well too. There is some experimentation with including Go in R https://github.com/rstats-go/gotest that I could try

**Comment by dimus** [comment]
I am connecting other languages via gRPC (https://rubygems.org/gems/gnparser) but for R there is no direct route to gRPC according to https://grpc.io/docs/. So connector to R would have to be in C++ I guess, and then binding to R? And it is RPC, so a bit less convenient and a little bit slower. I am considering to send Ruby and Scala parser to limbo, and concentrate on Go version because of the speed and cleaner parsing rules https://gitlab.com/gogna/gnparser/blob/master/grammar/grammar.peg._

**Comment by dimus** [comment]
My timezone is CST. I am free today for the rest of the day, tomorrow I am free after 10CST, and on Friday I am free after 11CST. Google hangout is a bit easier, as it is better supported than Skype on Linux

**Comment by sckott** [comment]
Of those options C++ would be best for R. 

Go does seem like a good single best implementation. 

How about 130 pm PST today? 330 CST Hangouts works for me. I'm at myrmecocystus@gmail.com

**Comment by dimus** [comment]
Sounds good @sckott, talk to you soon

**Comment by dimus** [comment]
Closing this, now it relates to Go gnparser

**Comment by dimus** [comment]
@sckott my Ruby parser now uses Go gnparser compiled to c library: https://github.com/GlobalNamesArchitecture/biodiversity

**Comment by sckott** [comment]
Thanks - has the C library that's created from the Go version changed much or at all since early  2019 when I last tried it?  Tried again briefly and I still can't get it to work

**Comment by dimus** [comment]
hm, the C-library appeared first time 6 months ago, so it is not the same thing we tried then.
https://gitlab.com/gogna/gnparser/-/issues/69

To use it in Ruby I used FFI
https://github.com/GlobalNamesArchitecture/biodiversity/blob/master/lib/biodiversity/parser.rb

**Comment by sckott** [comment]
Okay, right. I was looking at that file. In R, we have to do what FFI does in C, which I do not know :) I'll try it again at some point

**Comment by dimus** [comment]
You can also look at the Go to C functions here: 

https://gitlab.com/gogna/gnparser/-/blob/master/binding/main.go

**Comment by sckott** [comment]
thanks
