### ISSUE TITLE
Question. Can this identify scientific names (latin or greek words in scientific litrature)?

### ISSUE THREAD

**Issue by federicosan** [GlobalNamesArchitecture/gnparser#482]
Hi, thank you for reading this. I am searching for a list of scientific words or a tool that can identify scientific words (used for bacteria names for example usually Latin or Greek words) from an abstract title so I can properly italicize and bold them. Does this project include a dictionary of some kind?

Thank you.

**Comment by dimus** [comment]
https://github.com/gnames/gnfinder is a project specifically made for name-finding. You can also check https://gnrd.globalnames.org for web interface
